# Generated by Django 3.2.9 on 2021-11-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birth_month',
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_day',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
